safe-drop:
  enabled: true
  seconds: 10
  text-message:
    enabled: true
  actionbar-message:
    enabled: true
messages:
  no-permission: '&cYou do not have permission to do this!'
  drop-text-message: '&9Confirm drop by dropping item again!'
  drop-actionbar-message: '&9Confirm drop by dropping item again!'
  safedrop-off: '&cSafeDrop has been disabled!'
  safedrop-on: '&aSafeDrop has been enabled!'
  usage:
    - '&9&lTry,'
    - '&9/&8Safedrop off &7- Turns off safedrop'
    - '&9/&8Safedrop on &7- Turns on safedrop'