package dev.codedred.safedrop.utils;

import java.util.Arrays;
import java.util.List;

public class Items {

  public static List<String> getAllTools() {
    return Arrays.asList(
      "WOODEN_AXE",
      "WOODEN_HOE",
      "WOODEN_PICKAXE",
      "WOODEN_SHOVEL",
      "WOODEN_SWORD",
      "STONE_AXE",
      "STONE_HOE",
      "STONE_PICKAXE",
      "STONE_SHOVEL",
      "STONE_SWORD",
      "IRON_AXE",
      "IRON_HOE",
      "IRON_PICKAXE",
      "IRON_SHOVEL",
      "IRON_SWORD",
      "GOLDEN_AXE",
      "GOLDEN_HOE",
      "GOLDEN_PICKAXE",
      "GOLDEN_SHOVEL",
      "GOLDEN_SWORD",
      "DIAMOND_AXE",
      "DIAMOND_HOE",
      "DIAMOND_PICKAXE",
      "DIAMOND_SHOVEL",
      "DIAMOND_SWORD",
      "NETHERITE_AXE",
      "NETHERITE_HOE",
      "NETHERITE_PICKAXE",
      "NETHERITE_SHOVEL",
      "NETHERITE_SWORD"
    );
  }

  public static List<String> getAllSpawnEggs() {
    return Arrays.asList(
      "BAT_SPAWN_EGG",
      "BEE_SPAWN_EGG",
      "BLAZE_SPAWN_EGG",
      "CAT_SPAWN_EGG",
      "CAVE_SPIDER_SPAWN_EGG",
      "CHICKEN_SPAWN_EGG",
      "COD_SPAWN_EGG",
      "COW_SPAWN_EGG",
      "CREEPER_SPAWN_EGG",
      "DOLPHIN_SPAWN_EGG",
      "DONKEY_SPAWN_EGG",
      "DROWNED_SPAWN_EGG",
      "ELDER_GUARDIAN_SPAWN_EGG",
      "ENDERMAN_SPAWN_EGG",
      "ENDERMITE_SPAWN_EGG",
      "EVOKER_SPAWN_EGG",
      "FOX_SPAWN_EGG",
      "GHAST_SPAWN_EGG",
      "GUARDIAN_SPAWN_EGG",
      "HOGLIN_SPAWN_EGG",
      "HORSE_SPAWN_EGG",
      "HUSK_SPAWN_EGG",
      "LLAMA_SPAWN_EGG",
      "MAGMA_CUBE_SPAWN_EGG",
      "MOOSHROOM_SPAWN_EGG",
      "MULE_SPAWN_EGG",
      "OCELOT_SPAWN_EGG",
      "PANDA_SPAWN_EGG",
      "PARROT_SPAWN_EGG",
      "PHANTOM_SPAWN_EGG",
      "PIG_SPAWN_EGG",
      "PIGLIN_SPAWN_EGG",
      "PIGLIN_BRUTE_SPAWN_EGG",
      "PILLAGER_SPAWN_EGG",
      "POLAR_BEAR_SPAWN_EGG",
      "PUFFERFISH_SPAWN_EGG",
      "RABBIT_SPAWN_EGG",
      "RAVAGER_SPAWN_EGG",
      "SALMON_SPAWN_EGG",
      "SHEEP_SPAWN_EGG",
      "SHULKER_SPAWN_EGG",
      "SILVERFISH_SPAWN_EGG",
      "SKELETON_SPAWN_EGG",
      "SKELETON_HORSE_SPAWN_EGG",
      "SLIME_SPAWN_EGG",
      "SPIDER_SPAWN_EGG",
      "SQUID_SPAWN_EGG",
      "STRAY_SPAWN_EGG",
      "STRIDER_SPAWN_EGG",
      "TRADER_LLAMA_SPAWN_EGG",
      "TROPICAL_FISH_SPAWN_EGG",
      "TURTLE_SPAWN_EGG",
      "VEX_SPAWN_EGG",
      "VILLAGER_SPAWN_EGG",
      "VINDICATOR_SPAWN_EGG",
      "WANDERING_TRADER_SPAWN_EGG",
      "WITCH_SPAWN_EGG",
      "WITHER_SKELETON_SPAWN_EGG",
      "WOLF_SPAWN_EGG",
      "ZOGLIN_SPAWN_EGG",
      "ZOMBIE_SPAWN_EGG",
      "ZOMBIE_HORSE_SPAWN_EGG",
      "ZOMBIE_VILLAGER_SPAWN_EGG",
      "ZOOMBIEFIED_PIGLIN_SPAWN_EGG"
    );
  }

  public static List<String> getAllArmor() {
    return Arrays.asList(
      "LEATHER_HELMET",
      "LEATHER_CHESTPLATE",
      "LEATHER_LEGGINGS",
      "LEATHER_BOOTS",
      "CHAINMAIL_HELMET",
      "CHAINMAIL_CHESTPLATE",
      "CHAINMAIL_LEGGINGS",
      "CHAINMAIL_BOOTS",
      "IRON_HELMET",
      "IRON_CHESTPLATE",
      "IRON_LEGGINGS",
      "IRON_BOOTS",
      "GOLDEN_HELMET",
      "GOLDEN_CHESTPLATE",
      "GOLDEN_LEGGINGS",
      "GOLDEN_BOOTS",
      "DIAMOND_HELMET",
      "DIAMOND_CHESTPLATE",
      "DIAMOND_LEGGINGS",
      "DIAMOND_BOOTS",
      "NETHERITE_HELMET",
      "NETHERITE_CHESTPLATE",
      "NETHERITE_LEGGINGS",
      "NETHERITE_BOOTS"
    );
  }
}
